export const IPC = {
  TRANSLATE_LOADING: 'translate:loading',
  TRANSLATE_RESULT: 'translate:result',
  TRANSLATE_ERROR: 'translate:error',
  OVERLAY_CLOSE: 'overlay:close',
  OVERLAY_DRAG_START: 'overlay:drag-start',
  OVERLAY_DRAG_END: 'overlay:drag-end',
  OVERLAY_GET_POSITION: 'overlay:get-position',
  OVERLAY_SET_POSITION: 'overlay:set-position',
  OVERLAY_PASTE: 'overlay:paste',
  OVERLAY_RETONE: 'overlay:retone',
  SELECTION_ACTIVATE: 'selection:activate',
  SELECTION_DISMISS: 'selection:dismiss',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SAVE: 'settings:save',
  HOTKEY_CAPTURE: 'hotkey:capture',
  AUTH_SESSION: 'auth:session',
  AUTH_LOGIN: 'auth:login',
  AUTH_LOGOUT: 'auth:logout',
  AUTH_OPEN_LOGIN: 'auth:open-login',
  SESSION_CHANGED: 'session:changed',
  APP_VERSION: 'app:version',
  CAPTURE_INIT: 'capture:init',
  CAPTURE_COMPLETE: 'capture:complete',
  CAPTURE_CANCEL: 'capture:cancel'
} as const
